### ISSUE TITLE
Not able to load images from API(asynchronous)

### ISSUE THREAD

**Issue by keatwei** [f111fei/react-native-banner-carousel#2]
Hi
I'm currently having problem loading images from API, here is my [StackOverflow](https://stackoverflow.com/questions/48009345/how-to-make-react-native-banner-carousel-load-images-from-apiasynchronous).
https://stackoverflow.com/questions/48009345/how-to-make-react-native-banner-carousel-load-images-from-apiasynchronous 

Any suggestion on the asynchronous issue?

**Comment by f111fei** [comment]
Sorry, so late to response. Here is my suggestion.
```
render(){
    const images = this.props.carousels;
    if (!images || images.length === 0) {
        return null;
    }

    return(
        ......
        <Carousel
            autoplay
            autoplayTimeout={5000}
            loop
            index={0}
            showsPageIndicator={ false }
            pageSize={BannerWidth}
        >
        { images.map((image, index) => this.renderPage(image, index))}
        </Carousel>
        ......
    );
}
```
Don't render carousel when the image list length is 0.

**Comment by keatwei** [comment]
@f111fei yup. its working. thx

**Comment by shivamtiwari8736** [comment]
Hi @keatwei , Can you help me in passing JSON of array consisting of Objects as datasource. Please have a look at the issue opened by me: 
[How to pass JSON of Images as Data Source? ](https://github.com/f111fei/react-native-banner-carousel/issues/14#issue-505229246)
