### ISSUE TITLE
Invariant Violation: inputRange must be monotically increasing 0,1,0

### ISSUE THREAD

**Issue by Johncy1997** [f111fei/react-native-banner-carousel#4]
<Carousel
                
            autoplay
            autoplayTimeout={5000}
            loop
            index={0}
            showsPageIndicator={ false }
             pageSize={BannerWidth}
            height={250}
            itemWidth={sliderWidth}
      itemHeight={itemHeight}
        >
        { 
          this.props.data.banner.map((image, index) => {
          console.log("carousel started to render")
          return(
            <View key={index}> 
           {                          console.log("The image url is "+image.BannerUrl)
             }
              <Image source={{uri: image.BannerUrl}} style={{flex:1,width: BannerWidth, height: BannerHeight,resizeMode:'contain'}}/>
            </View>
          )
        })}
        </Carousel>

plz someone tell me how to change this code.

**Comment by f111fei** [comment]
What's your `renderIndicator` ?

**Comment by Johncy1997** [comment]
Sorry, i didn't use any renderIndicator here.Simply used the sample in usage section here.

**Comment by f111fei** [comment]
`this.props.data.banner.length` must be > 0.

**Comment by Johncy1997** [comment]
Yes it is >0 only.It's value is [{..},{..},{..}].

**Comment by f111fei** [comment]
pls update to `react-native-banner-carousel@1.0.3`
